---
- name: create an EC2 instance on aws
  hosts: localhost
  vars:
    aws_region: ap-south-1
    instance_type: t2.micro
    ami_id: ami-xxxxxxxxx
    key_name: xxxxxx
    instance_name: Ansible_host_server
    vpc_subnet_id: subnet-xxxxxxxx
  tasks:
    - name: create a ec2 instance first time
      amazon.aws.ec2_instance: 
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID')}}"
        aws_secret_key: "{{lookup('env', 'AWS_SECRET_KEY')}}"
        region: "{{ aws_region }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        key_name: "{{ key_name }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        count: 1
      register: ec2_instance
    - name: Print ec2 instance details
      debug:
        var: ec2_instance.instances
...
